### ISSUE TITLE
problem with the config on the documentation

### ISSUE THREAD

**Issue by dummys** [jomwells/ambihue#8]
Hi, 

I have a problem with your config. My switches.yaml looks like this:

```yaml
- platform: philips_ambilight+hue
  name: Ambilight+Hue
  host: 192.168.2.8
  username: !secret philips_username
  password: !secret philips_password
  id: 2131230774 # ambilight_hue_off node id. Default is 2131230774, but some newer TVs use 2131230778 instead.
  scan_interval: 5
```

I get an error stated "Missing switches" in the entry for philips_ambilight+hue.
What Iam doing wrong ? 
Thanks
